### ISSUE TITLE
[Bug] Creating more than 1 createCustomError() overwrites the "name" of the error.

### ISSUE THREAD

**Issue by MSNev** [nevware21/ts-utils#148]
This appears to be because the prototype of the function passed [here](https://github.com/nevware21/ts-utils/blob/7ca9036e5b54f645b55e23837981fd7ab50feb22/lib/src/helpers/customError.ts#L89-L95) to the `_createCustomError` is always the same and the `_createCustomError` is replacing it [here](https://github.com/nevware21/ts-utils/blob/7ca9036e5b54f645b55e23837981fd7ab50feb22/lib/src/helpers/customError.ts#L33)

**Comment by nev21** [comment]
I bumped this to a P1 as this is actually corrupting the main "Error" prototype name assigning the last custom error name to the Error.prototype.name so event `new Error()` will be assigned / use this name.
