### ISSUE TITLE
[Bug] Tree-Shaking is not working properly

### ISSUE THREAD

**Issue by nev21** [nevware21/ts-utils#230]
**Describe the bug**
Consuming the latest version of the library `0.10.2` results in the following code being left behind in `@nevware21/ts-async` 

```js
var arrIndexOf = _unwrapFunction(INDEX_OF, ArrProto);
    _unwrapFunction(LAST_INDEX_OF, ArrProto);

    var arrSlice = _unwrapFunction(SLICE, ArrProto);

    var fnCall = _unwrapInstFunction(CALL);
```
Where the `LAST_INDEX_OF` (which is not used), is not getting tree-shaken from the build

**To Reproduce**
1. Clone '@nevware21/ts-async`
2. Rebuild and review the `dist/es5/amd/ts-async.js` (actually most of the formats not just `amd`)
3. See unreferenced functions / properties not getting tree-shaken out of the generated code

**Expected behavior**
The unused functions should get tree-shaken out of existence in the consuming modules

**Comment by MSNev** [comment]
Issue is still occurring for some "other" usages, specifically in ApplicationInsights for the `strSymSplit` function

```js

var strSplit = _unwrapFunction("split", StrProto);
hasSymbol() ? _unwrapFunction("split", StrProto) : polyStrSymSplit;
```

Trialing some local "fixes", it's possible to suppress this further by tagging the `hasSymbol` with the `/*#__NO_SIDE_EFFECTS__*/` so that rollup knows that when it's not referenced it can be dropped.

**Comment by MSNev** [comment]
Please add this to all of the "accessor" functions like `getXXX()`, `hasXXX()` when they don't have any side-effects as the package.json sideEffects: false doesn't always work.
