### ISSUE TITLE
[doc] TSDoc Error During Build

### ISSUE THREAD

**Issue by siyuniu-ms** [nevware21/ts-utils#350]
Hi,
I encountered the following TSDoc error when installing this package and running npm run build in my project. Could you please update the comments to resolve these errors?

Thank you!
Warning: node_modules/@nevware21/ts-utils/dist/types/ts-utils.d.ts:492:4 - (tsdoc-param-tag-missing-hyphen) The @param block should be followed by a parameter name and then a hyphen
Warning: node_modules/@nevware21/ts-utils/dist/types/ts-utils.d.ts:493:4 - (tsdoc-param-tag-missing-hyphen) The @param block should be followed by a parameter name and then a hyphen
Warning: node_modules/@nevware21/ts-utils/dist/types/ts-utils.d.ts:495:4 - (tsdoc-unsupported-tag) The TSDoc tag "@remarks" is not supported by this tool
Warning: node_modules/@nevware21/ts-utils/dist/types/ts-utils.d.ts:3591:29 - (tsdoc-code-span-missing-delimiter) The code span is missing its closing backtick
Warning: node_modules/@nevware21/ts-utils/dist/types/ts-utils.d.ts:6203:4 - (tsdoc-param-tag-missing-hyphen) The @param block should be followed by a parameter name and then a hyphen

**Comment by nev21** [comment]
Ok, this is a larger issue than expected as there was no existing tsdoc.json defintion defined and the api-extractor config was ignoring warnings. So this is a larger issue than expected and is taking longer than expected to fix all of the typedoc issues, so it might be another day or two before I have these (ts-utils and ts-async) addressed and released.

One note: the `@remarks` is expected and you should add this to your tsdoc.json as an expected block comment
include in your `supportForTags` section of tsdoc.json
`"@remarks": true`
